In [2]:
import pandas as pd
df=pd.read_csv("Bank_Marketing_Original_Data.csv")

In [3]:
df.shape

(45211, 17)

In [4]:
df["Job"].value_counts()

Job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [5]:
df["Marital"].value_counts()

Marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

In [6]:
df["Education"].value_counts()

Education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [7]:
df["contact"].value_counts()

contact
cellular     29285
unknown      13020
telephone     2906
Name: count, dtype: int64

In [8]:
df["Month"].value_counts()

Month
may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: count, dtype: int64

In [9]:
df.sample()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
43747,62,retired,married,secondary,no,3114,no,no,cellular,18,may,243,2,186,1,success,yes

In [10]:
df["poutcome"].value_counts()

poutcome
unknown    36959
failure     4901
other       1840
success     1511
Name: count, dtype: int64

In [11]:
ordinal_data=df[["Education"]]

In [12]:
target_data=df[["TARGET"]]

In [13]:
from sklearn.preprocessing import OrdinalEncoder

In [14]:
oe=OrdinalEncoder(categories=[["unknown","primary","secondary","tertiary"]])

In [15]:
ordinal_data=oe.fit_transform(ordinal_data)

In [16]:
ordinal_data

array([[3.],
       [2.],
       [2.],
       ...,
       [2.],
       [2.],
       [2.]], shape=(45211, 1))

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le=LabelEncoder()

In [19]:
target_data=le.fit_transform(target_data)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [20]:
target_data

array([0, 0, 0, ..., 1, 0, 0], shape=(45211,))

In [21]:
df.sample()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
26342,33,blue-collar,married,primary,no,1416,yes,no,cellular,20,nov,60,1,-1,0,unknown,no

In [22]:
nominal_data=df[["Job","Marital","Default","Housing","Loan","contact","Month","poutcome"]]

In [23]:
nominal_data

                Job   Marital Default Housing Loan    contact Month poutcome
0        management   married      no     yes   no    unknown   may  unknown
1        technician    single      no     yes   no    unknown   may  unknown
2      entrepreneur   married      no     yes  yes    unknown   may  unknown
3       blue-collar   married      no     yes   no    unknown   may  unknown
4           unknown    single      no      no   no    unknown   may  unknown
...             ...       ...     ...     ...  ...        ...   ...      ...
45206    technician   married      no      no   no   cellular   nov  unknown
45207       retired  divorced      no      no   no   cellular   nov  unknown
45208       retired   married      no      no   no   cellular   nov  success
45209   blue-collar   married      no      no   no  telephone   nov  unknown
45210  entrepreneur   married      no      no   no   cellular   nov    other

[45211 rows x 8 columns]

In [24]:
df["Marital"].value_counts()

Marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
ohe=OneHotEncoder()

In [27]:
nominal_data=ohe.fit_transform(nominal_data)

In [28]:
nominal_data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 361688 stored elements and shape (45211, 40)>